### ISSUE TITLE
Admin/Owner chunk claiming

### ISSUE THREAD

**Issue by Millificent** [FTBTeam/FTB-Utilities-Chunks#22]
Hi,

Is there any expected time for "server owned" chunks or chunk editing facility available?

With so many servers now having mods to allow economies (ATM 3 Remix) it would be a great feature to allow shops with interactions however at the moment the perms impact all chunks.

Thanks :)

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Utilities-Chunks/issues/1 no ETAs
